apiVersion: apps/v1
kind: Deployment
metadata:
 name: businessapp1
 labels:
    app: businessapp1
spec:
 replicas: 2
 selector:
    matchLabels:
      app: businessapp1
 template:
    metadata:
       labels:
        app: businessapp1
    spec:
      containers:
      - name: businessapp1container
        image: us.icr.io/ibmperumf2/businessapp1
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: businessapp1
spec:
 type: NodePort
 selector:
   app: businessapp1
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32089
 selector:
   app: businessapp1
